"""se agrega picture

Revision ID: 80713839f4ea
Revises: 4b092bee893d
Create Date: 2022-11-18 10:21:22.196575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80713839f4ea'
down_revision = '4b092bee893d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('picture', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='messages_pkey')
    )
    op.drop_table('message')
    # ### end Alembic commands ###
